version: '3.8'

services:
  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    ports:
      - 3000:3000
    environment:
      - http://localhost:8000
    volumes:
      - .:/app
    depends_on:
      - backend

  backend:
    build:
      context: ./backend
      dockerfile: go.Dockerfile
    ports:
      - 8000:8000
    volumes:
      - .:/app/backend

    env_file:
      - ./backend/.env  