version: '3'
services:
  auth-frontend:
    image: sachinparihar/auth-frontend:latest
    ports:
      - '3000:3000'
    environment:
      - PORT=3000

  auth-backend:
    image: sachinparihar/auth-backend:latest
    ports:
      - '8000:8000'
   